### ISSUE TITLE
better error message when pycryptol can't find cryptol-server

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/pycryptol#10]
(e.g., when it's not on your path).

Right now I get the rather unfriendly:

```
Traceback (most recent call last):
  File "testInstall.py", line 2, in <module>
    cry = cryptol.Cryptol()
  File "/usr/local/lib/python2.7/site-packages/cryptol/cryptol.py", line 64, in __init__
    stderr=null)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by acfoltzer** [comment]
We should similarly handle the case where the ZeroMQ shared library is not in the dynamic linker's path.

**Comment by acfoltzer** [comment]
We now explicitly check for file-not-found, and also check for an early exit from the spawned server. The former should take care of @dylanmc's original report; the latter should at least provide the exit code for when a shared library isn't found (trying to launch `false` as an example):

```
>>> cry = Cryptol('false')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/acfoltzer/src/pycryptol/cryptol/cryptol.py", line 87, in __init__
    'with exit code {:d}'.format(cryptol_server, result)
__main__.CryptolServerError: Cryptol server executable 'false' exited unexpectedly with exit code 1
```
